version: 2.1
orbs:
    codecov: codecov/codecov@1.0.2

jobs:
    node:
        docker:
            - image: circleci/node:latest
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                  name: prebuild dependencies
                  command: sudo npm install -g pnpm
            - run:
                  name: install and run tests
                  command: pnpm install && pnpm test

            - run:
                  name: get test coverage
                  command: pnpm coverage

            - codecov/upload:
                  file: 'coverage.lcov'

workflows:
    version: 2
    build:
        jobs:
            - node
