# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5
  node: circleci/node@4.7.0
workflows:
  upload-to-codecov:
    jobs:
      - node/test:
          post-steps:
            - codecov/upload